---

- name: "Overwrite SonarQube download url for community edition"
  set_fact:
    sonar_download_url: "{{ __sonar_ce_download_url }}"
  when:
  - sonar_download_url is not defined
  - sonar_edition == "community"

- name: "Overwrite SonarQube download url for developer edition"
  set_fact:
    sonar_download_url: "{{ __sonar_de_download_url }}"
  when:
  - sonar_download_url is not defined
  - sonar_edition == "developer"

- name: "Overwrite SonarQube download url for enterprise edition"
  set_fact:
    sonar_download_url: "{{ __sonar_ee_download_url }}"
  when:
  - sonar_download_url is not defined
  - sonar_edition == "enterprise"

- name: "Overwrite SonarQube plugin base url"
  set_fact:
    sonar_plugin_baseurl: "{{ __sonar_plugin_baseurl }}"
  when: sonar_plugin_baseurl is not defined

- name: "Overwrite SonarQube commercial plugin base url"
  set_fact:
    sonar_commercial_plugin_baseurl: "{{ __sonar_commercial_plugin_baseurl }}"
  when: sonar_commercial_plugin_baseurl is not defined
